# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: 合同会社Red-Gamma
email: your-email@domain.com
author: Your Name
description: > # "Write an awesome description for your new site here.
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: "Copyright &copy; 2024 Red-Gamma Corp. All Rights Reserved."
# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  # - title: twitter
  #   url: https://twitter.com/SBootstrap
  # - title: github
  #   url: https://github.com/IronSummitMedia/startbootstrap
  - title: linkedin
    url: https://jp.linkedin.com/in/%E6%BD%A4%E4%B8%80-%E5%8C%97%E5%B7%9D-b16a19211
